# Generated by Django 5.2.2 on 2025-07-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('seller', 'Seller')], default='', max_length=10),
        ),
    ]
