# Generated by Django 5.2.2 on 2025-07-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={},
        ),
    ]
