# Generated by Django 5.2.2 on 2025-07-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_user_type_sellermodel_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='CustomerProfile',
        ),
        migrations.RenameModel(
            old_name='SellerModel',
            new_name='SellerProfile',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
