# Generated by Django 5.2.2 on 2025-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charges',
            field=models.CharField(choices=[('free', 'Free Delivery'), ('paid', 'Paid Delivery')], default='free', max_length=10),
        ),
    ]
