# Generated by Django 5.2.2 on 2025-06-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='Category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='id',
            new_name='SubCategory_id',
        ),
    ]
